// Inlines the Cairo woff2 files as data URLs (src/fonts.generated.ts) so renders never fetch fonts.
import {readFileSync, writeFileSync} from 'node:fs';

const out = {};
for (const w of [400, 500, 600, 700, 800])
  for (const sub of ['arabic', 'latin'])
    out[`${sub}-${w}`] = readFileSync(new URL(`../public/fonts/cairo-${sub}-${w}-normal.woff2`, import.meta.url)).toString('base64');
writeFileSync(
  new URL('../src/fonts.generated.ts', import.meta.url),
  `// Generated by scripts/gen-fonts.mjs — do not edit.\nexport const CAIRO_WOFF2: Record<string, string> = ${JSON.stringify(out)};\n`,
);
console.log('fonts inlined');
